import json
from collections import defaultdict


foo = {
    "took": 2,
    "timed_out": False,
    "_shards": {"total": 1, "successful": 1, "skipped": 0, "failed": 0},
    "hits": {
        "total": 1,
        "max_score": 1.0278128,
        "hits": [
            {
                "_index": "properties-v14",
                "_type": "Property",
                "_id": "655",
                "_score": 1.0278128,
                "_source": {
                    "billing_cycle": "weekly",
                    "cancellation_checked": True,
                    "country_name": "United Kingdom",
                    "booking_journey": "manual",
                    "landlord_name": "Homes for Students 11)",
                    "city_slug": "manchester",
                    "property_type": "student-accommodation",
                    "name": "Manchester Court",
                    "area_slug": "manchester-city",
                    "popularity": 0.0,
                    "city_name": "Manchester",
                    "no_visa_no_pay": True,
                    "geo_point": {"lon": -2.22841, "lat": 53.4575},
                    "waitinglist_enabled": False,
                    "covid19_policy": False,
                    "slug": "manchester-court",
                    "hero_image": {
                        "source": "property-17173-5eb72ba15cb9571215e31462943c7cba.jpeg",
                        "alt_text": None,
                    },
                    "reviews": {"all_locale": {"count": 3, "average_rating": 3.0}},
                    "currency_code": "GBP",
                    "facilities": [
                        {
                            "translations": {
                                "es_la": {"name": "Onsite Manager"},
                                "el_gr": {"name": "Onsite Manager"},
                                "it_it": {"name": "Gestore in loco"},
                                "ru_ru": {"name": "Onsite Manager"},
                                "tr_tr": {"name": "Onsite Manager"},
                                "pt_br": {"name": "Onsite Manager"},
                                "th_th": {"name": "Onsite Manager"},
                                "fr_fr": {"name": "Onsite Manager"},
                                "ja_jp": {"name": "Onsite Manager"},
                                "el_cy": {"name": "Onsite Manager"},
                                "de_de": {"name": "Onsite Manager"},
                                "zh_tw": {"name": "Onsite Manager"},
                                "zh_hk": {"name": "Onsite Manager"},
                                "en_gb": {"name": "Onsite Manager"},
                                "vi_vn": {"name": "Onsite Manager"},
                                "ko_kr": {"name": "Onsite Manager"},
                                "en_us": {},
                                "es_es": {"name": "Onsite Manager"},
                                "zh_cn": {"name": "公寓经理"},
                            },
                            "name": "Onsite Manager",
                            "rank": 80,
                            "slug": "onsite_manager",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Entertainment Area/ Room"},
                                "el_gr": {"name": "Entertainment Area/ Room"},
                                "it_it": {"name": "Sala / area intrattenimento"},
                                "ru_ru": {"name": "Entertainment Area/ Room"},
                                "tr_tr": {"name": "Entertainment Area/ Room"},
                                "pt_br": {"name": "Entertainment Area/ Room"},
                                "th_th": {"name": "Entertainment Area/ Room"},
                                "fr_fr": {"name": "Entertainment Area/ Room"},
                                "ja_jp": {"name": "Entertainment Area/ Room"},
                                "el_cy": {"name": "Entertainment Area/ Room"},
                                "de_de": {"name": "Entertainment Area/ Room"},
                                "zh_tw": {"name": "Entertainment Area/ Room"},
                                "zh_hk": {"name": "Entertainment Area/ Room"},
                                "en_gb": {"name": "Entertainment Area/ Room"},
                                "vi_vn": {"name": "Entertainment Area/ Room"},
                                "ko_kr": {"name": "Entertainment Area/ Room"},
                                "en_us": {},
                                "es_es": {"name": "Entertainment Area/ Room"},
                                "zh_cn": {"name": "娱乐区/室"},
                            },
                            "name": "Entertainment Area/ Room",
                            "rank": 100,
                            "slug": "entertainment_area",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Fully Furnished"},
                                "el_gr": {"name": "Fully Furnished"},
                                "it_it": {"name": "Completamente arredato"},
                                "ru_ru": {"name": "Fully Furnished"},
                                "tr_tr": {"name": "Fully Furnished"},
                                "pt_br": {"name": "Fully Furnished"},
                                "th_th": {"name": "Fully Furnished"},
                                "fr_fr": {"name": "Fully Furnished"},
                                "ja_jp": {"name": "Fully Furnished"},
                                "el_cy": {"name": "Fully Furnished"},
                                "de_de": {"name": "Fully Furnished"},
                                "zh_tw": {"name": "Fully Furnished"},
                                "zh_hk": {"name": "Fully Furnished"},
                                "en_gb": {"name": "Fully Furnished"},
                                "vi_vn": {"name": "Fully Furnished"},
                                "ko_kr": {"name": "Fully Furnished"},
                                "en_us": {},
                                "es_es": {"name": "Fully Furnished"},
                                "zh_cn": {"name": "提供家具"},
                            },
                            "name": "Fully Furnished",
                            "rank": 140,
                            "slug": "fully_furnished",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Communal Laundry (Coin-operated)"},
                                "el_gr": {"name": "Communal Laundry (Coin-operated)"},
                                "it_it": {"name": "Lavanderia comune (a gettoni)"},
                                "ru_ru": {"name": "Communal Laundry (Coin-operated)"},
                                "tr_tr": {"name": "Communal Laundry (Coin-operated)"},
                                "pt_br": {"name": "Communal Laundry (Coin-operated)"},
                                "th_th": {"name": "Communal Laundry (Coin-operated)"},
                                "fr_fr": {"name": "Communal Laundry (Coin-operated)"},
                                "ja_jp": {"name": "Communal Laundry (Coin-operated)"},
                                "el_cy": {"name": "Communal Laundry (Coin-operated)"},
                                "de_de": {"name": "Communal Laundry (Coin-operated)"},
                                "zh_tw": {"name": "Communal Laundry (Coin-operated)"},
                                "zh_hk": {"name": "Communal Laundry (Coin-operated)"},
                                "en_gb": {"name": "Communal Laundry (Coin-operated)"},
                                "vi_vn": {"name": "Communal Laundry (Coin-operated)"},
                                "ko_kr": {"name": "Communal Laundry (Coin-operated)"},
                                "en_us": {},
                                "es_es": {"name": "Communal Laundry (Coin-operated)"},
                                "zh_cn": {"name": "公共洗衣房（投币式）"},
                            },
                            "name": "Communal Laundry (Coin-operated)",
                            "rank": 170,
                            "slug": "laundry_coin",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Wifi"},
                                "el_gr": {"name": "Wifi"},
                                "it_it": {"name": "Wi-Fi"},
                                "ru_ru": {"name": "Wifi"},
                                "tr_tr": {"name": "Wifi"},
                                "pt_br": {"name": "Wifi"},
                                "th_th": {"name": "Wifi"},
                                "fr_fr": {"name": "Wifi"},
                                "ja_jp": {"name": "Wifi"},
                                "el_cy": {"name": "Wifi"},
                                "de_de": {"name": "Wifi"},
                                "zh_tw": {"name": "Wifi"},
                                "zh_hk": {"name": "Wifi"},
                                "en_gb": {"name": "Wi-Fi"},
                                "vi_vn": {"name": "Wifi"},
                                "ko_kr": {"name": "Wifi"},
                                "en_us": {},
                                "es_es": {"name": "Wifi"},
                                "zh_cn": {"name": "无线网络"},
                            },
                            "name": "Wifi",
                            "rank": 230,
                            "slug": "wifi_free",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Water"},
                                "el_gr": {"name": "Water"},
                                "it_it": {"name": "Acqua"},
                                "ru_ru": {"name": "Water"},
                                "tr_tr": {"name": "Water"},
                                "pt_br": {"name": "Water"},
                                "th_th": {"name": "Water"},
                                "fr_fr": {"name": "Water"},
                                "ja_jp": {"name": "Water"},
                                "el_cy": {"name": "Water"},
                                "de_de": {"name": "Water"},
                                "zh_tw": {"name": "Water"},
                                "zh_hk": {"name": "Water"},
                                "en_gb": {"name": "Water"},
                                "vi_vn": {"name": "Water"},
                                "ko_kr": {"name": "Water"},
                                "en_us": {},
                                "es_es": {"name": "Water"},
                                "zh_cn": {"name": "水费"},
                            },
                            "name": "Water",
                            "rank": 260,
                            "slug": "water_free",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Electricity"},
                                "el_gr": {"name": "Electricity"},
                                "it_it": {"name": "Luce"},
                                "ru_ru": {"name": "Electricity"},
                                "tr_tr": {"name": "Electricity"},
                                "pt_br": {"name": "Electricity"},
                                "th_th": {"name": "Electricity"},
                                "fr_fr": {"name": "Electricity"},
                                "ja_jp": {"name": "Electricity"},
                                "el_cy": {"name": "Electricity"},
                                "de_de": {"name": "Electricity"},
                                "zh_tw": {"name": "Electricity"},
                                "zh_hk": {"name": "Electricity"},
                                "en_gb": {"name": "Electricity"},
                                "vi_vn": {"name": "Electricity"},
                                "ko_kr": {"name": "Electricity"},
                                "en_us": {},
                                "es_es": {"name": "Electricity"},
                                "zh_cn": {"name": "电费"},
                            },
                            "name": "Electricity",
                            "rank": 310,
                            "slug": "electricity_free",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Heating"},
                                "el_gr": {"name": "Heating"},
                                "it_it": {"name": "Riscaldamento"},
                                "ru_ru": {"name": "Heating"},
                                "tr_tr": {"name": "Heating"},
                                "pt_br": {"name": "Heating"},
                                "th_th": {"name": "Heating"},
                                "fr_fr": {"name": "Heating"},
                                "ja_jp": {"name": "Heating"},
                                "el_cy": {"name": "Heating"},
                                "de_de": {"name": "Heating"},
                                "zh_tw": {"name": "Heating"},
                                "zh_hk": {"name": "Heating"},
                                "en_gb": {"name": "Heating"},
                                "vi_vn": {"name": "Heating"},
                                "ko_kr": {"name": "Heating"},
                                "en_us": {},
                                "es_es": {"name": "Heating"},
                                "zh_cn": {"name": "暖气"},
                            },
                            "name": "Heating",
                            "rank": 340,
                            "slug": "heating_free",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Gas"},
                                "el_gr": {"name": "Gas"},
                                "it_it": {"name": "Gas"},
                                "ru_ru": {"name": "Gas"},
                                "tr_tr": {"name": "Gas"},
                                "pt_br": {"name": "Gas"},
                                "th_th": {"name": "Gas"},
                                "fr_fr": {"name": "Gas"},
                                "ja_jp": {"name": "Gas"},
                                "el_cy": {"name": "Gas"},
                                "de_de": {"name": "Gas"},
                                "zh_tw": {"name": "Gas"},
                                "zh_hk": {"name": "Gas"},
                                "en_gb": {"name": "Gas"},
                                "vi_vn": {"name": "Gas"},
                                "ko_kr": {"name": "Gas"},
                                "en_us": {},
                                "es_es": {"name": "Gas"},
                                "zh_cn": {"name": "煤气费"},
                            },
                            "name": "Gas",
                            "rank": 400,
                            "slug": "gas_free",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "CCTV / Surveillance Cameras"},
                                "el_gr": {"name": "CCTV / Surveillance Cameras"},
                                "it_it": {"name": "Videosorveglianza"},
                                "ru_ru": {"name": "CCTV / Surveillance Cameras"},
                                "tr_tr": {"name": "CCTV / Surveillance Cameras"},
                                "pt_br": {"name": "CCTV / Surveillance Cameras"},
                                "th_th": {"name": "CCTV / Surveillance Cameras"},
                                "fr_fr": {"name": "CCTV / Surveillance Cameras"},
                                "ja_jp": {"name": "CCTV / Surveillance Cameras"},
                                "el_cy": {"name": "CCTV / Surveillance Cameras"},
                                "de_de": {"name": "CCTV / Surveillance Cameras"},
                                "zh_tw": {"name": "CCTV / Surveillance Cameras"},
                                "zh_hk": {"name": "CCTV / Surveillance Cameras"},
                                "en_gb": {"name": "CCTV / Surveillance Cameras"},
                                "vi_vn": {"name": "CCTV / Surveillance Cameras"},
                                "ko_kr": {"name": "CCTV / Surveillance Cameras"},
                                "en_us": {},
                                "es_es": {"name": "CCTV / Surveillance Cameras"},
                                "zh_cn": {"name": "闭路电视/监控摄像机"},
                            },
                            "name": "CCTV / Surveillance Cameras",
                            "rank": 430,
                            "slug": "cctv",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Maintenance Team (Daytime only)"},
                                "el_gr": {"name": "Maintenance Team (Daytime only)"},
                                "it_it": {
                                    "name": "Addetti alla manutenzione (solo di giorno)"
                                },
                                "ru_ru": {"name": "Maintenance Team (Daytime only)"},
                                "tr_tr": {"name": "Maintenance Team (Daytime only)"},
                                "pt_br": {"name": "Maintenance Team (Daytime only)"},
                                "th_th": {"name": "Maintenance Team (Daytime only)"},
                                "fr_fr": {"name": "Maintenance Team (Daytime only)"},
                                "ja_jp": {"name": "Maintenance Team (Daytime only)"},
                                "el_cy": {"name": "Maintenance Team (Daytime only)"},
                                "de_de": {"name": "Maintenance Team (Daytime only)"},
                                "zh_tw": {"name": "Maintenance Team (Daytime only)"},
                                "zh_hk": {"name": "Maintenance Team (Daytime only)"},
                                "en_gb": {"name": "Maintenance Team (Daytime only)"},
                                "vi_vn": {"name": "Maintenance Team (Daytime only)"},
                                "ko_kr": {"name": "Maintenance Team (Daytime only)"},
                                "en_us": {},
                                "es_es": {"name": "Maintenance Team (Daytime only)"},
                                "zh_cn": {"name": "维修团队（仅日间）"},
                            },
                            "name": "Maintenance Team (Daytime only)",
                            "rank": 470,
                            "slug": "maintenance_team_daytime_only",
                        },
                        {
                            "translations": {
                                "es_la": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "el_gr": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "it_it": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "ru_ru": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "tr_tr": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "pt_br": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "th_th": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "fr_fr": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "ja_jp": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "el_cy": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "de_de": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "zh_tw": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "zh_hk": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "en_gb": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "vi_vn": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "ko_kr": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "en_us": {},
                                "es_es": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                                "zh_cn": {
                                    "name": "Controlled Access Gate (Locked gate)"
                                },
                            },
                            "name": "Controlled Access Gate (Locked gate)",
                            "rank": 530,
                            "slug": "controlled_access_gate_locked_gate",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "No Smoking"},
                                "el_gr": {"name": "No Smoking"},
                                "it_it": {"name": "Vietato fumare"},
                                "ru_ru": {"name": "No Smoking"},
                                "tr_tr": {"name": "No Smoking"},
                                "pt_br": {"name": "No Smoking"},
                                "th_th": {"name": "No Smoking"},
                                "fr_fr": {"name": "No Smoking"},
                                "ja_jp": {"name": "No Smoking"},
                                "el_cy": {"name": "No Smoking"},
                                "de_de": {"name": "No Smoking"},
                                "zh_tw": {"name": "No Smoking"},
                                "zh_hk": {"name": "No Smoking"},
                                "en_gb": {"name": "No Smoking"},
                                "vi_vn": {"name": "No Smoking"},
                                "ko_kr": {"name": "No Smoking"},
                                "en_us": {},
                                "es_es": {"name": "No Smoking"},
                                "zh_cn": {"name": "禁止吸烟"},
                            },
                            "name": "No Smoking",
                            "rank": 540,
                            "slug": "no_smoking",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "Communal Kitchen"},
                                "el_gr": {"name": "Communal Kitchen"},
                                "it_it": {"name": "Cucina in comune"},
                                "ru_ru": {"name": "Communal Kitchen"},
                                "tr_tr": {"name": "Communal Kitchen"},
                                "pt_br": {"name": "Communal Kitchen"},
                                "th_th": {"name": "Communal Kitchen"},
                                "fr_fr": {"name": "Communal Kitchen"},
                                "ja_jp": {"name": "Communal Kitchen"},
                                "el_cy": {"name": "Communal Kitchen"},
                                "de_de": {"name": "Communal Kitchen"},
                                "zh_tw": {"name": "Communal Kitchen"},
                                "zh_hk": {"name": "Communal Kitchen"},
                                "en_gb": {"name": "Communal Kitchen"},
                                "vi_vn": {"name": "Communal Kitchen"},
                                "ko_kr": {"name": "Communal Kitchen"},
                                "en_us": {},
                                "es_es": {"name": "Communal Kitchen"},
                                "zh_cn": {"name": "公共厨房"},
                            },
                            "name": "Communal Kitchen",
                            "rank": 10050,
                            "slug": "cooking_facilities",
                        },
                        {
                            "translations": {
                                "es_la": {"name": "TV in Room"},
                                "el_gr": {"name": "TV in Room"},
                                "it_it": {"name": "TV in camera"},
                                "ru_ru": {"name": "TV in Room"},
                                "tr_tr": {"name": "TV in Room"},
                                "pt_br": {"name": "TV in Room"},
                                "th_th": {"name": "TV in Room"},
                                "fr_fr": {"name": "TV in Room"},
                                "ja_jp": {"name": "TV in Room"},
                                "el_cy": {"name": "TV in Room"},
                                "de_de": {"name": "TV in Room"},
                                "zh_tw": {"name": "TV in Room"},
                                "zh_hk": {"name": "TV in Room"},
                                "en_gb": {"name": "TV in Room"},
                                "vi_vn": {"name": "TV in Room"},
                                "ko_kr": {"name": "TV in Room"},
                                "en_us": {},
                                "es_es": {"name": "TV in Room"},
                                "zh_cn": {"name": "电视机（卧室）"},
                            },
                            "name": "TV in Room",
                            "rank": 10190,
                            "slug": "tv_in_room",
                        },
                    ],
                    "updated_at": "2021-07-02T18:22:03.342287+00:00",
                    "area_name": "Manchester City Centre",
                    "property_type_priority": 1,
                    "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                    "total_beds": 99,
                    "translations": {
                        "ja_jp": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "it_it": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "ko_kr": {
                            "country_name": "United Kingdom",
                            "city_name": "맨체스터",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "fr_fr": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "zh_tw": {
                            "country_name": "英國",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "en_gb": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "zh_hk": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "tr_tr": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "es_es": {
                            "country_name": "Reino Unido",
                            "city_name": "Mánchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "el_cy": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "pt_br": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "vi_vn": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "ru_ru": {
                            "country_name": "United Kingdom",
                            "city_name": "Манчестер",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "th_th": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "el_gr": {
                            "country_name": "United Kingdom",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "de_de": {
                            "country_name": "Vereinigtes Königreich",
                            "city_name": "Manchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "zh_cn": {
                            "country_name": "英国",
                            "city_name": "曼彻斯特",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "es_la": {
                            "country_name": "United Kingdom",
                            "city_name": "Mánchester",
                            "headline": "Fall in love with Manchester’s live music scene, Victorian architecture and vibrant student culture when you live at Manchester Court",
                        },
                        "en_us": {},
                    },
                    "video": "",
                    "no_place_no_pay": True,
                    "country_slug": "uk",
                    "rank": 24.0,
                    "gallery_images": [
                        {
                            "alt_text": None,
                            "source": "property-17174-6484d1cad0655a4a8038f2f14579d76a.jpeg",
                        },
                        {
                            "alt_text": None,
                            "source": "property-17175-1b188c405bf59cd2bf510f45f8405ac2.jpeg",
                        },
                        {
                            "alt_text": None,
                            "source": "property-17176-c6d726e05ca1de5a615f468fc543137d.jpeg",
                        },
                        {
                            "alt_text": None,
                            "source": "property-17177-0727f23f1d741a92e11916e11cdd4663.jpeg",
                        },
                    ],
                    "rank_weight": 7.0,
                    "book_now": False,
                    "is_from": True,
                    "sort_price": 131,
                    "sort_state": 0,
                    "minimum_price": "131.00",
                    "availability": "good",
                    "state": "available_with_price",
                    "units": [
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "212.00",
                                    "listing_id": 1000214147,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                }
                            ],
                            "minimum_price": "212.00",
                            "name": "Gold Studio",
                            "unit_type_id": 10059234,
                            "kitchen_count": None,
                            "is_from": False,
                            "links": [],
                            "bathroom_type": "private",
                            "category": "entire-place",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "149.00",
                                    "listing_id": 1000214148,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                }
                            ],
                            "minimum_price": "149.00",
                            "name": "Gold 2 Bed Apartment",
                            "unit_type_id": 10059243,
                            "kitchen_count": None,
                            "is_from": False,
                            "links": [],
                            "bathroom_type": "shared",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "140.00",
                                    "listing_id": 1000214151,
                                    "tenancy_length_value": "48",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-08",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "132.00",
                                    "listing_id": 1000214153,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                            ],
                            "minimum_price": "132.00",
                            "name": "Gold 3 Bed Apartment",
                            "unit_type_id": 10059255,
                            "kitchen_count": None,
                            "is_from": True,
                            "links": [],
                            "bathroom_type": "shared",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "139.00",
                                    "listing_id": 1000214155,
                                    "tenancy_length_value": "48",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "good",
                                    "move_out": "2022-08-08",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "available_with_price",
                                    "minimum_discounted_price": None,
                                },
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "131.00",
                                    "listing_id": 1000214156,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "good",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "available_with_price",
                                    "minimum_discounted_price": None,
                                },
                            ],
                            "minimum_price": "131.00",
                            "name": "Gold 4 Bed Apartment",
                            "unit_type_id": 10059272,
                            "kitchen_count": None,
                            "is_from": True,
                            "links": [],
                            "bathroom_type": "shared",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "130.00",
                                    "listing_id": 1000214158,
                                    "tenancy_length_value": "48",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-08",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "122.00",
                                    "listing_id": 1000214160,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                            ],
                            "minimum_price": "122.00",
                            "name": "Bronze 4 Bed Apartment",
                            "unit_type_id": 10059284,
                            "kitchen_count": None,
                            "is_from": True,
                            "links": [],
                            "bathroom_type": "shared",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "142.00",
                                    "listing_id": 1000214162,
                                    "tenancy_length_value": "48",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-08",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "137.00",
                                    "listing_id": 1000214164,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                            ],
                            "minimum_price": "137.00",
                            "name": "Gold Plus 4 Bed Apartment",
                            "unit_type_id": 10059295,
                            "kitchen_count": None,
                            "is_from": True,
                            "links": [],
                            "bathroom_type": "shared",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                        {
                            "listings": [
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "150.00",
                                    "listing_id": 1000214166,
                                    "tenancy_length_value": "51",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-27",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                                {
                                    "move_out_type": "exactly_match",
                                    "minimum_price": "160.00",
                                    "listing_id": 1000214168,
                                    "tenancy_length_value": "48",
                                    "num_nominations_available": 0,
                                    "available_to": None,
                                    "min_duration": None,
                                    "listing_type": "not-specific",
                                    "tenancy_length_type": "equals",
                                    "availability": "fully-booked",
                                    "move_out": "2022-08-08",
                                    "move_in": "2021-09-04",
                                    "available_from": None,
                                    "move_in_type": "exactly_match",
                                    "maximum_price": None,
                                    "tenancy_periods": [
                                        {
                                            "end_months": ["2022-08"],
                                            "start_month": "2021-09",
                                        }
                                    ],
                                    "state": "sold_out",
                                    "minimum_discounted_price": None,
                                },
                            ],
                            "minimum_price": "150.00",
                            "name": "Platinum Ensuite",
                            "unit_type_id": 10059304,
                            "kitchen_count": None,
                            "is_from": True,
                            "links": [],
                            "bathroom_type": "private",
                            "category": "private-room",
                            "minimum_discounted_price": None,
                        },
                    ],
                    "categories": [
                        {
                            "minimum_price": None,
                            "is_from": False,
                            "minimum_discounted_price": None,
                            "slug": "shared-room",
                        },
                        {
                            "minimum_price": "131.00",
                            "is_from": True,
                            "minimum_discounted_price": None,
                            "slug": "private-room",
                        },
                        {
                            "minimum_price": "212.00",
                            "is_from": False,
                            "minimum_discounted_price": None,
                            "slug": "entire-place",
                        },
                    ],
                    "commute_times": {
                        "university": [
                            {
                                "driving": 813.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`Bu@j@gBvAa@b@gA`AyChC{F|EgGhFkBxAe@`@cAbAaCvBqChCoAbA{@z@cAz@{@r@_@ZYsA[w@iEgIm@qAaBiDc@w@SYGCKKOScAcBGLFMe@u@e@Z_AbCo@~Ag@rA",
                                "university_slug": "university-of-salford",
                                "transit": 678.0,
                                "walking": 2205.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnABl@GlL@fBH|CJ`BLfAD~BI`Ai@hBw@zBoBlGy@|G_EOuEE{@Dk@DcAPs@BS?gAGs@GcAKqC]mCImCCe@BiB\\}Af@sE|BuE|By@^cBl@g@DMFQ\\q@tAOTQLI?MGOKk@eAi@_@IAKBWR_@JqA~@wEpB{@Vq@D]Ia@MyAWu@Oe@SKIOKOYWw@JgA^eCV{B@}@I{CGq@G[KSUS_Bi@[Oa@k@YaAI[y@wD[w@iEgIm@qAaBiDc@w@SYGCKKSj@i@hAcAdCo@fBeC}D",
                                "bicycling": None,
                                "recommended_value": 3.5,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@uB`B_ChBcB`BkGhFoBfByAjA_DlCiAbAmBxAe@`@_A`AwAnAoCfC_CnB{@z@k@b@s@p@_At@sApAm@d@KFIIQYyAaCiCeEqGeKkAmBg@rA",
                            },
                            {
                                "driving": 427.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`Bu@j@gBvAa@b@gA`AyChC{F|EH^KFf@hCBE`Bt@FCHZTSbAy@`AdEz@hEqCbCg@f@m@AEGKOKMAC",
                                "university_slug": "university-of-manchester",
                                "transit": 761.0,
                                "walking": 1499.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnABl@GlL@fBH|CJ`BLfAD~BI`Ai@hBw@zBoBlGy@|G_EOuEE{@Dk@DcAPs@BS?gAGs@GcAKqC]mCImCCe@BiB\\}Af@sE|BuE|By@^cBl@g@DMFQ\\q@tAOTQLI?MGOKk@eAU]CW?]Xw@h@qAt@kBJc@DiB?yBKaEKw@]w@[IY[Ma@Ie@Js@\\aBLSLMPGPAPJ",
                                "bicycling": None,
                                "recommended_value": 3.5,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@w@p@TrAAPUl@@VtBpJv@dEQL]ZQNeB~AcCjBgFrEqCbCg@f@m@AEGKOKMAC",
                            },
                            {
                                "driving": 439.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`BIFDVEWHGtBaBt@a@",
                                "university_slug": "royal-northern-college-of-music",
                                "transit": 483.0,
                                "walking": 864.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnAuA?wDIy@CuEIkNa@UBkE`CKJABHXJv@nBlNJXHLYVc@d@_@l@Ud@U^e@\\a@N_DP}BF}@HwA^Ck@k@_DScAUo@cAoEcCiLYiANQfBwArB{AbAy@h@Y",
                                "bicycling": None,
                                "recommended_value": 14,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@y@l@",
                            },
                            {
                                "driving": 852.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FEqCM@LAAaBAq@C[?GULYFOL{Az@kB|@mAd@gA`@gAZ{Ah@wBhAmCnBk@b@c@`@aCjCoDlE}CnDm@x@u@x@uCvCg@b@i@f@cAt@u@`@uB`Bu@j@gBvAa@b@gA`A_GdFqIfHkAbAkBxAkAdA{@z@uFdFoAbA{@z@cAz@{@r@_@ZYsA[w@{@}AsAiCINHQy@}AEM_@p@w@fBe@jA_@z@IMHLUd@m@tAeAxCo@tAiBjDUp@a@xAU^i@pD?Fq@pEM`Am@jFa@tEc@tDq@dI_@hBa@hAOb@_@l@{@fAs@t@uB|B]\\STBv@BhCBn@F`@PxBBbBCbEArC?dD@|CJdL@~E@dG@rALfCNlEAhBEv@UtBg@fCqApEe@|Bo@zDk@hES`Aa@xBc@tAELDFEGITK\\o@lB[jAI\\CIASBWd@uAAs@IWIKEG]@y@Bq@BSDAIAGCGKIEAE?IFGLADMGWAyAT",
                                "university_slug": "university-of-manchester-fallowfield-campus",
                                "transit": 2313.0,
                                "walking": 3963.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnABl@GlL@fBH|CJ`BLfAD~BI`Ai@hBw@zBoBlGy@|G_EOuEE{@Dk@DcAPs@BS?gAGs@GcAKqC]mCImCCe@BiB\\}Af@sE|BuE|By@^cBl@g@DMFQ\\q@tAKn@OhDUnGOxBKv@ObFEvB]dJQtB]tCUpAg@lBy@`CcElJk@jAw@nAq@|@a@d@y@p@sA|@_An@e@^[j@]r@O^[jAUbBSvCWvBW`DeAhLId@[tDWtC}@hJsAxNgC`WiAbLOfBYjBYhA@N@LI\\Yr@Mt@C|@CjAGZM^Ud@WTQNUDU?a@Uc@g@]q@Mq@Eu@MiEAe@Iu@I_@O]_A}AsBcDuCoDiBuB{@{@{@q@gAu@s@_@e@Qe@K_@?kBHs@AOEMO]e@Ec@j@aBAs@IWIKEG]@y@Bq@BSD?D?JGRIJK?KGGQAS?IEGMEg@DcAN",
                                "bicycling": None,
                                "recommended_value": 1.4000000000000001,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@uB`B_ChBcB`BkGhFoBfByAjA_DlCiAbAmBxAe@`@_A`AwAnAoCfC_CnB{@z@k@b@s@p@_At@sApAm@d@w@p@_@n@[t@W`AKh@[zCGr@YzEYpEo@vIYrDkAbMe@bFY~B]j@cA|@_B~AyDbESPYHm@b@ULFh@c@f@oAxAc@b@SLWF[?MCoAg@k@W?zA?zCAtD@zFB`FDjI?pIB|BVtFBfCKbBa@bDm@nBw@rCQt@Wz@WtA}@hGQjBUjAo@lCM`@[RIDWFQD_ABuAFGB?GACCGCGKGEAE@IFEJADECMEg@DcAN",
                            },
                            {
                                "driving": 391.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`BIFDVEWk@b@gBvAoAnA",
                                "university_slug": "bpp-university-in-manchester",
                                "transit": 441.0,
                                "walking": 1056.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnAuA?wDIy@CuEIkNa@UBkE`CKJABHXJv@nBlNJXHLYVc@d@_@l@Ud@U^e@\\a@N_DP}BF}@HwA^Ck@k@_DScAUo@cAoEcCiLYiAQPm@j@",
                                "bicycling": None,
                                "recommended_value": 14,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@uB`B_ChBcB`BIF",
                            },
                            {
                                "driving": 575.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`Bu@j@gBvAa@b@gA`AyChC{F|EgGhFkBxAe@`@cAbAaCvBqChCoAbA{@z@cAz@{@r@_@ZYsA[w@i@_AGNDSj@bAZv@XrA^[z@s@x@s@",
                                "university_slug": "the-manchester-college",
                                "transit": 625.0,
                                "walking": 1680.0,
                                "driving_polyline": "k|geIpfrLo@F?v@@lF?tEq@lUItCEnABl@GlL@fBH|CJ`BLfAD~BI`Ai@hBw@zBoBlGy@|G_EOuEE{@Dk@DcAPs@BS?gAGs@GcAKqC]mCImCCe@BiB\\}Af@sE|BuE|By@^cBl@g@DMFQ\\q@tAOTQLI?MGOKk@eAU]CW?]Xw@h@qAt@kBJc@DiB?yBKaEKw@]w@[IY[i@OgAx@yClCuC~BgA|@IFKDKG_@i@u@kAE]E[q@aDy@}Da@yBoAbA{@z@",
                                "bicycling": None,
                                "recommended_value": 3.5,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@uB`B_ChBcB`BkGhFoBfByAjA_DlCiAbAmBxAe@`@_A`AwAnAoCfC_CnB{@z@",
                            },
                            {
                                "driving": 467.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqEAs@CeAUNYFy@h@WNCWBVVOx@i@f@m@b@[\\Av@g@jBoAz@e@jAs@dBs@fCw@DIl@a@r@s@PCp@u@bAuAHYXc@n@o@n@s@NEb@SbCeAx@c@fAc@jAu@hAgA~AkAdBuAdAk@jBo@jCiAb@[^a@lC{D`@g@^U\\Sd@KbA[`@IPIVAn@HxBf@h@NhAVhATd@Hf@@?W?Vg@Ae@IFyC?uAAqAGgCGSMYIMJs@Dc@?_@Aa@Ic@Qe@]EQ@",
                                "university_slug": "university-of-law",
                                "transit": 943.0,
                                "walking": 1500.0,
                                "driving_polyline": "k|geIpfrLo@FGqEAs@CeAGUb@[\\Ad@WlBsA`@WpBiAhBy@fCu@DIl@a@r@s@PCp@u@bAuAHYXc@n@o@n@s@NEb@Sr@YnB_ArAo@h@Wn@a@dAcAXUlCsBbAs@|@_@|Bw@~Au@TO\\YrBwC|@qA\\YNICo@G}ASkJAM|CaAn@QnBo@jBm@XEz@O",
                                "bicycling": None,
                                "recommended_value": 3.5,
                                "walking_polyline": "k|geIpfrLlGo@@aDEmAQgECc@EWb@UTO~@a@nAc@j@Qp@SDBLEt@e@`@[L_@xAiBZa@HYXc@TQn@u@Z[LEPKx@[tCuAfAc@jAu@lBeBrCyBbAm@r@YnBo@bBw@b@[^a@`DuE\\YNICo@G}AIsCIwEAM|CaAn@Qf@QrDkAdAQNC",
                            },
                            {
                                "driving": 603.0,
                                "bicycling_polyline": None,
                                "transit_polyline": "k|geIpfrLo@FGqE?a@e@@uCvAEYE_@eAf@mAd@gA`@sBl@o@VqAp@wA~@gCjBc@`@_AbA{AfBgFfGkAtAm@x@kEpEg@b@i@f@cAt@u@`@uB`Bu@j@gBvAa@b@gA`AyChC{F|EgGhFkBxAe@`@cAbAaCvBqChCoAbA{@z@cAz@{@r@_@ZYsA[w@{@}AsAiCINHQy@}AEM@CxA_BTUr@s@BEGKOY",
                                "university_slug": "manchester-metropolitan-university",
                                "transit": 642.0,
                                "walking": 1873.0,
                                "driving_polyline": "k|geIpfrLo@FGqEAs@CeAUNYFy@h@}C|A[LJiIBmADiDN_KDqEEcBK_CMcBq@x@q@x@iB|BeCxCoIhKqIhKkJtL}CxDoB`CmRrUW^KXCFyAxBuDrE}@p@y@|@ODWV_@`@e@f@y@f@oBvAmAx@iAl@_AZwA`@s@h@]b@MV{@tAq@z@We@",
                                "bicycling": None,
                                "recommended_value": 3.5,
                                "walking_polyline": "k|geIpfrLo@F?v@sFXk@?o@Jk@qA_@{@Os@UF}Ad@o@VwBhAmCnB_Ar@_@`@wBbCiEhF}BjCm@x@kEpEg@b@i@f@cAt@u@`@uB`B_ChBcB`BkGhFoBfByAjA_DlCiAbAaB}GEe@@My@gDESEF_@^i@Xg@ZeBtAcBdAu@^oA\\w@TWPk@f@[j@{@tAEHMSQ]",
                            },
                        ]
                    },
                    "maximum_price": None,
                    "minimum_discounted_price": None,
                    "universities": None,
                    "links": None,
                    "special_offers": None,
                    "required_documents": None,
                },
                "inner_hits": {
                    "units": {
                        "hits": {
                            "total": 1,
                            "max_score": 1.0278128,
                            "hits": [
                                {
                                    "_index": "properties-v14",
                                    "_type": "Property",
                                    "_id": "655",
                                    "_nested": {"field": "units", "offset": 3},
                                    "_score": 1.0278128,
                                    "inner_hits": {
                                        "units.listings": {
                                            "hits": {
                                                "total": 2,
                                                "max_score": 1.0278128,
                                                "hits": [
                                                    {
                                                        "_index": "properties-v14",
                                                        "_type": "Property",
                                                        "_id": "655",
                                                        "_nested": {
                                                            "field": "units",
                                                            "offset": 3,
                                                            "_nested": {
                                                                "field": "listings",
                                                                "offset": 0,
                                                            },
                                                        },
                                                        "_score": 1.0278128,
                                                    },
                                                    {
                                                        "_index": "properties-v14",
                                                        "_type": "Property",
                                                        "_id": "655",
                                                        "_nested": {
                                                            "field": "units",
                                                            "offset": 3,
                                                            "_nested": {
                                                                "field": "listings",
                                                                "offset": 1,
                                                            },
                                                        },
                                                        "_score": 1.0278128,
                                                    },
                                                ],
                                            }
                                        }
                                    },
                                }
                            ],
                        }
                    }
                },
            }
        ],
    },
}


def _load_units_and_listings_by_filter(data: dict) -> dict:
    inner_hits = data["hits"]["hits"][0]["inner_hits"]

    units = defaultdict(list)
    for u in inner_hits["units"]["hits"]["hits"]:

        for l in u["inner_hits"]["units.listings"]["hits"]["hits"]:

            units[l["_nested"]["offset"]].append(l["_nested"]["_nested"]["offset"])

    # Remove non-matching listings
    for u_offset, l_offset in units.items():
        exclude = set(
            range(0, len(data["hits"]["hits"][0]["_source"]["units"][u_offset]["listings"]))
        ) - set(l_offset)
        for index in sorted(exclude, reverse=True):
            del data["hits"]["hits"][0]["_source"]["units"][u_offset]["listings"][index]

    # Remove non-matching units
    include = units.keys()
    exclude = set(range(0, len(data["hits"]["hits"][0]["_source"]["units"]))) - set(
        include
    )
    for index in sorted(exclude, reverse=True):
        del data["hits"]["hits"][0]["_source"]["units"][index]

    return data["hits"]["hits"][0]["_source"]["units"]


if __name__ == "__main__":
    print(json.dumps(_load_units_and_listings_by_filter(foo)))
